### ISSUE TITLE
Implement NextFit

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework4#1]
Implement NextFit. This algorithm is similar to FirstFit, as it doesn't consider size (other than whether or not it is large enough), although it needs to remember where it left off. This search continues from the last index it placed a process in, looping around if necessary.

**Comment by fdaniels110** [comment]
I'll work on this.  I remember how it works from class so it shouldn't be
too bad

**Comment by flip40** [comment]
Awesome! I forgot to mention in my initial write-up of this, I wrote up some classes, Memory.java and its private inner class Block.java, to make finding and inspecting free memory space easy, as well as inserting a process into the free space, so be sure to make use of those. I completed FirstFit, so check that if seeing examples of using the methods in Memory.java would help.

**Comment by fdaniels110** [comment]
Implementation was Pull Requested with finalized code.
