### ISSUE TITLE
Implement BestFit

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework4#2]
Implement BestFit. This search tries to find the free block that will be closest to the process' required memory size while still being large enough to fit it. Something in the spirit of the old max() search (finding the largest integer in an array) should work well here.

Be sure to check and make use of the Memory and Block classes (Block is an inner class of Memory), they are there to make finding free blocks of memory, inspecting them, and inserting a process into them manageable. FirstFit is already finished and has example use of the related methods if that helps.

**Comment by ErickN80** [comment]
I'll try this one.
