### ISSUE TITLE
Copy process arrays, clean memory, clean runningProcesses

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework4#6]
I believe I currently have the process arrays directly used by the simulation function. This is bad as it ruins the arrays after the first simulation. As such we need to provide a copy for each simulation to use. This will require a copy constructor for Process, don't forget that just adding the elements to a new array will simply get two arrays pointing to the same processes, not two lists with copies of the processes.

We also need to clean memory before each simulation and clean runningProcesses.

**Comment by fdaniels110** [comment]
Lol I was in the middle of doing this. Good timing. I'll have a fix posted in an independent branch. Memory should be cleared too as well as Runningprocesses

**Comment by flip40** [comment]
Haha, well post an issue when you see these, I don't have to be the only one to make them. If anyone finds something that needs to be done, make a post (especially if you are going to do it, then assign yourself to it). Just to avoid two people doing the same thing, as then one persons won't get used and all that.
Also you would be correct, I missed it in my description but while looking this over noticed those other two need to be cleaned as well, I'll add that to the description.

**Comment by fdaniels110** [comment]
Ill post an issue next time.
